### PR TITLE
[BUGFIX] Additional Classes must be public to get Overriding/Extending Controller Classes working

### PR DESCRIPTION
**Pull request by Patta**
Extending New/EditController will not working in TYPO3 10.4.x because of deprecated DI notation.

This PR fixes issue #321 and #314
includes already PR #254 and #255

### CODE REVIEW

**Review by sbusemann — CHANGES_REQUESTED** [review]
there are exceptions now, f.e. (1/1) ArgumentCountError
Too few arguments to function In2code\Femanager\Controller\AbstractController::__construct(), 0 passed in /app/.Build/Web/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3423 and exactly 6 expected

**Comment by Patta** [comment]
@sbusemann This is out of my context of usage of this extension. I tried to get the extension running for use on a website with admin approval and custom fields. This PR is certainly a WIP for other use cases such as opt-in etc, which I have not fully tested.

**Comment by Patta** [comment]
Updated the PR with changes from version 6.2.0. 
_The core cache needs to be flushed to rebuild the compiled symfony container._

**Comment by Patta** [comment]
@sbusemann maybe @spoonerWeb can help us here :)

**Comment by Patta** [comment]
Updated the PR with changes from develop.

**Comment by sbusemann** [comment]
@Patta can you please fix the cs violation?
