### ISSUE TITLE
Class Psr\EventDispatcher\EventDispatcherInterface does not exist. Reflection failed.

### ISSUE THREAD

**Issue by medarob** [in2code-de/femanager#246]
After the update to v6.0 it seems that there is an issue in TYPO3 9.5.19.

The following error appeared:
![grafik](https://user-images.githubusercontent.com/33951787/87045225-ecac0200-c1f7-11ea-8bee-b65bff2ffdb6.png)

there was also this error

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Too few arguments to function In2code\Femanager\Domain\Service\SendMailService::__construct(), 0 passed in /var/www/typo3/web/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3689 and exactly 2 expected | ArgumentCountError thrown in file /var/www/typo3/web/typo3conf/ext/femanager/Classes/Domain/Service/SendMailService.php in line 48. Requested URL: https://www.domain.tld/login/?tx_femanager_pi1%%5Baction%%5D=new&tx_femanager_pi1%%5Bcontroller%%5D=New `

There were no other changes.
After the downgrade to v5.3, the FE works again.
